[package]
name = "ollama"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.8.0"
dirs = "5.0.1"
dotenv = "0.15.0"
futures-util = "0.3.30"
ollama-rs = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
